WIP: Adding Multiple events
HackSocNotts/HackSocNotts.github.io pull request #160
Opened 2020-10-10 11:55 UTC by Emersont1

Adding all the events via this pull request

2020-10-10 12:08 UTC, tashBayliss approved these changes, later dismissed

2020-10-10 22:08 UTC, aaronosher requested changes
Other than the FF bit needing to be removed, @AksanDotDev hasn't confirmed that date yet, it looks good to me

2020-10-10 22:08 UTC, aaronosher commented on src/_events/2020-ff-quirks/summary.md
> +A look at the software quirks of the Final Fantasy Games
Can remove for now, please

2020-10-10 22:08 UTC, aaronosher commented on src/_events/2020-ff-quirks/manifest.yml
> +  banner: 2020-ff-quirks/banner.jpg
Can remove for now, please

2020-10-10 22:08 UTC, aaronosher commented on src/_events/2020-ff-quirks/description.md
> + From speedrunners to lore nerds and all sorts in between push and break games, taking them to pieces to see how they work. Join Alexi and Leanne on a journey through the bugs and exploits that the F
Can remove for now, please

2020-10-10 22:09 UTC, aaronosher commented on src/_events/2020-ff-quirks/manifest.yml
> +  banner: 2020-ff-quirks/banner.jpg
Also, the date is off by a month

2020-10-17 16:58 UTC, aaronosher approved these changes

2020-10-17 17:02 UTC, merged