Fixes #16
HackSocNotts/HackSocNotts.github.io pull request #17
Opened 2018-10-14 18:55 UTC by DanielCordell

Also changed toby's email to be hacksecretary@
Also also removed Helena's details.

2018-10-14 18:55 UTC, DanielCordell commented
Tabs spacing issue, 1 sec

2018-10-14 19:27 UTC, erinosher requested changes
That's brilliant. However, I've been using <first_name>@hacksocnotts.co.uk for people.

2018-10-14 19:28 UTC, DanielCordell commented
That's fine, was just trying something out 👌

2018-10-15 16:17 UTC, erinosher approved these changes

2018-10-15 16:17 UTC, merged